name: Workflow

'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up working directory
        run: mkdir -p /home/runner/work/prog5121-poe-submission-Ashdiii/prog5121-poe-submission-Ashdiii/src

      - name: List contents of root directory
        run: ls

      - name: List contents of src directory
        working-directory: ./src
        run: ls

      - name: Compile classes
        working-directory: ./src
        run: |
          javac -cp "../testresources/junit-platform-console-standalone-1.6.0.jar" "./registrationandlogin/Registration.java" "./registrationandlogin/Task.java" "../test/test/registrationandlogin/RegistrationTest.java"

      - name: List contents of src directory after compile
        working-directory: ./src/registrationandlogin
        run: ls

      - name: Create testresources/packageName directory
        run: mkdir -p ./testresources/registrationandlogin

      - name: Copy compiled classes to testresources directory
        working-directory: ./src/registrationandlogin
        run: cp Registration.class Task.class ../../testresources/registrationandlogin

      - name: Copy compiled Test classes to testresources directory
        working-directory: ./test/test/registrationandlogin
        run: cp RegistrationTest.class ../../../testresources/registrationandlogin

      - name: List contents of testresources/registrationandlogin directory
        working-directory: ./testresources/registrationandlogin
        run: ls

